sudo: false
language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn install
- yarn add codecov.io
script:
- yarn build
- yarn test --coverage
notifications:
  slack: 
    rooms: 
      - secure: "QT2zqfgP6ccF34zvLiAwCpMdN7ecLxHn6FVFDfLzN9Gzg7xu1ntkkmI3yWyXuvJIo/4qxz+sYcMbPpGuneCUc+Y3htIC/cn1qWDXQYw9itTmzUSqejZDo+IyY9PIbW/ID1R5Im6la8/DUmdg4d0qRihmLUkyde+l/MQaWY2NIvLTa4gZLzt/LpJfVCo2osLJixJR4+IwGuX2gBPS0Q8QnBWVoodRhpb8bxonLjwaRvoyvHA0oYczX0nn2x3jUy6IXnv7txEk0I8JHlVNzA9+lZAHVKMEAPJBbCaLXLrQ0Z8dLXcMqA//QtQUUD9T/Zgr0wtJ6Ns61ItrDZ9xgsFpV3kNROjbM7rxJ7/n1hXx4VOF4uiWQ0sIcyP4IjXFjdDA2eTIiG1BGxdFgwlT/F5J8Kb5OXuA37/koC4t4jhhJv7ogi8zrmnZmbyKWS/zwYMtZkJE7ThnhFMKpOomxLFCDbrfHKB1H2PkIa/kuVvZBgZjxDhjPYob8pNU6eoEab2H7YCVo9ldBLbarzNQceWgF76kzzNTcwg+Bt/QfdVRJM9ivMpxwOFdmxq92L93vy8po9ar2l1aIHiNYRnT+wxwCnVLiHYSIOiRrZ6rKqKi9wafDYYKTWkbG+qw0OAIAXtolYycxcmKzrpMGkdkoIeaLBMZLjLdXAQWLFKHn0aSIcw="
    on_success: always # default: change
    on_failure: always # default: always
  email:
    recipients:
      - jhoerr@iu.edu
      - jhoerr@gmail.com
    on_success: always # default: change
    on_failure: always # default: always
after_success:
- cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
