# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build_test:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout 
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: 
         command: |
           yarn build
           yarn test -w 1 --coverage
           cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  publish_guide:
    docker:
      - image: circleci/node:8
    working_directory: ~/repo
    steps:
      - checkout 
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          command: |
            git config --global user.email "iubot@iu.edu"
            git config --global user.name "IU Bot"
            yarn publish-guide
workflows:
  version: 2
  build-test-and-publish:
    jobs:
      - build_test:
          filters:
            branches:
              ignore:
                - gh-pages
      - publish_guide:
          requires:
            - build_test
          filters:
            branches:
              only:
                - master
                - feature/circleci
