export const TestUtils = {
  ButtonGroup: { testId: "buttonGroup_testId" },
  SegmentedButton: { testId: "segmentedButton_testId" },
  RivetIcons: { testId: "rivetIcon_testId" },
  Dropdown: { testId: "testId" },
  Header: {
    skipLinkTestId: "skip-link-testId",
    anchorTestId: "header-anchor-testId",
    searchWrapperTestId: "search-wrapper-testId",
    navButtonToggleTestId: "nav-button-toggle-testId",
    menuButtonToggleTestId: "menu-button-toggle-testId",
    menuContainer: "menu-container-testId",
    menuItemsContainer: "menu-items-container-testId",
    navListItem: "nav-list-item-testId",
    headerNav: "header-nav-testId",
    searchToggleButton: "search-toggle-button-testId",
    searchButton: "search-button-testId",
    searchForm: "search-form-testId",
    searchInput: "search-input-testId",
    secondaryNav: "secondary-nav-testId",
    secondaryNavContainer: "nav-secondary-container-testId",
    secondaryNavToggle: "secondary-nav-toggle",
  },
};
