export const TestUtils = {
  ButtonGroup: { testId: "buttonGroup_testId" },
  SegmentedButton: { testId: "segmentedButton_testId" },
  RivetIcons: { testId: "rivetIcon_testId" },
  Dialog: {
    dialogHeaderTestId: "dialogHeader__testId",
    underlayDivTestId: "underlayDiv__testId",
    dialogBodyTestId: "dialogBody__testId",
    dialogControlsTestId: "dialogControlsTestId__testId",
  },
  Dropdown: { testId: "testId" },
  Header: {
    skipLinkTestId: "skip-link__testid",
    anchorTestId: "header-anchor__testid",
    searchWrapperTestId: "search-wrapper__testid",
    navButtonToggleTestId: "nav-button-toggle__testid",
    menuButtonToggleTestId: "menu-button-toggle__testid",
    menuAnchorTestId: "menu-anchor-toggle__testid",
    menuContainerTestId: "menu-container__testid",
    menuItemsContainerTestId: "menu-items-container__testid",
    navListItemTestId: "nav-list-item__testid",
    headerNavTestId: "header-nav__testid",
    searchToggleButtonTestId: "search-toggle-button__testid",
    searchButtonTestId: "search-button__testid",
    searchFormTestId: "search-form__testid",
    searchInputTestId: "search-input__testid",
    secondaryNavTestId: "secondary-nav__testid",
    secondaryNavContainerTestId: "nav-secondary-container__testid",
    secondaryNavToggleTestId: "secondary-nav-toggle__testid",
    avatarShortNameTestId: "avatar-short-name__testid",
    avatarUsernameTestId: "avatar-username__testid",
    headerWidthDivTestId: "header-width__testid",
  },
  Checkbox: { testId: "testId" },
  File: { testId: "testId" },
  RadioButton: { testId: "testId" },
  Table: { testId: "testId" },
  Footer: { testId: "testId" },
};
