export const TestUtils = {
  ButtonGroup: { testId: "buttonGroup_testId" },
  SegmentedButton: { testId: "segmentedButton_testId" },
  RivetIcons: { testId: "rivetIcon_testId" },
  Dropdown: { testId: "testId" },
  Header: {
    skipLinkTestId: "skip-link__testId",
    anchorTestId: "header-anchor__testId",
    searchWrapperTestId: "search-wrapper__testId",
    navButtonToggleTestId: "nav-button-toggle__testId",
    menuButtonToggleTestId: "menu-button-toggle__testId",
    menuContainerTestId: "menu-container__testId",
    menuItemsContainerTestId: "menu-items-container__testId",
    navListItemTestId: "nav-list-item__testId",
    headerNavTestId: "header-nav__testId",
    searchToggleButtonTestId: "search-toggle-button__testId",
    searchButtonTestId: "search-button__testId",
    searchFormTestId: "search-form__testId",
    searchInputTestId: "search-input__testId",
    secondaryNavTestId: "secondary-nav__testId",
    secondaryNavContainerTestId: "nav-secondary-container__testId",
    secondaryNavToggleTestId: "secondary-nav-toggle__testId",
  },
};
